# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Maniacgeek"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "http://mister.maniacgeek.net/"
tags = [hugo theme]
features = [minimalist, "light", "responsive design"]
min_version = 0.1

[author]
  name = "Houssen Moshinaly"
  homepage = ""

# If porting an existing theme
[original]
  name = "Robust"
  homepage = "http://themes.gohugo.io/robust/"
  repo = "https://github.com/dim0627/hugo_theme_robust"
