# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Maniacgeek"
license = "MIT"
licenselink = "https://github.com/HoussenMoshine/hugo-theme-maniacgeek/blob/master/LICENSE.md"
description = " A fast and ultra minimalist theme for Hugo"
homepage = "https://github.com/HoussenMoshine/hugo-theme-maniacgeek"
tags = [hugo theme, minimalist, responsive design, hugo]
features = [minimalist, "light", "responsive design"]
min_version = 0.1

[author]
  name = "Houssen Moshinaly"
  homepage = "https://mister.maniacgeek.net/"

# If porting an existing theme
[original]
  name = "Robust"
  homepage = "http://themes.gohugo.io/robust/"
  repo = "https://github.com/dim0627/hugo_theme_robust"
